## Assignment-2

#### Section A: Data Structures & Control Structures

##### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [22]:
# create list
list = [10, 20, 30, 40, 50]
print("Original List:", list)

Original List: [10, 20, 30, 40, 50]


##### -> Append

In [23]:
# Append
list.append(60)
print("After append(60):", list)

After append(60): [10, 20, 30, 40, 50, 60]


##### -> Extend

In [24]:
# Extend
list.extend([70, 80])
print("After extend([70, 80]):", list)

After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]


##### -> Remove

In [25]:
# Remove
list.remove(40)
print("After remove(40):", list)

After remove(40): [10, 20, 30, 50, 60, 70, 80]


##### -> Pop

In [26]:
# pop
popped = list.pop()
print("After pop():", list)
print("Popped element:", popped)

After pop(): [10, 20, 30, 50, 60, 70]
Popped element: 80


##### -> index

In [27]:
# index
index_val = list.index(30)
print("Index of 30:", index_val)


Index of 30: 2


##### -> Count

In [28]:
# count
count_val = list.count(20)
print("Count of 20:", count_val)


Count of 20: 1


##### -> Sort

In [29]:
# Sort
list.sort()
print("After sort():", list)


After sort(): [10, 20, 30, 50, 60, 70]


##### -> Reverse

In [30]:
# Reverse
list.reverse()
print("After reverse():", list)

After reverse(): [70, 60, 50, 30, 20, 10]


##### -> Clear

In [31]:
# Clear
list.clear()
print("After clear():", list)

After clear(): []


##### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [32]:
students = ("alfiya", "prashanth", "nithin")
print("Original Tuple:", students)


Original Tuple: ('alfiya', 'prashanth', 'nithin')


In [33]:
students[1]="rakshitha"
students

TypeError: 'tuple' object does not support item assignment

##### Explanation:

A tuple is immutable,

which means: Once created, you cannot change, add, or remove elements

You can convert the tuple to a list, change it, then convert back:

In [1]:
students = ("alfiya", "prashanth", "nithin")

temp = list(students)   # convert to list
temp[1] = "rakshitha"      
students = tuple(temp)  # convert back to tuple

print("Updated Tuple:", students)

Updated Tuple: ('alfiya', 'rakshitha', 'nithin')


##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [19]:
s = {1,2,2,3,4,4,5,6}

print("Set:", s)

Set: {1, 2, 3, 4, 5, 6}


##### Explanation (simple):

You gave values: {1, 2, 3, 4, 4, 5, 2, 6} But sets do not allow duplicates, 

so: 

4 is repeated → kept only once 2 is repeated → kept only once

##### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [20]:
person = {
    "name": "Ravi",
    "age": 22,
    "city": "Bangalore"
}
print("Original Dictionary:", person)


person["age"] = 25 # update age

person["email"] = "ravi@gmail.com" # add new key

print("Updated Dictionary:", person)

Original Dictionary: {'name': 'Ravi', 'age': 22, 'city': 'Bangalore'}
Updated Dictionary: {'name': 'Ravi', 'age': 25, 'city': 'Bangalore', 'email': 'ravi@gmail.com'}


##### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [24]:
age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter your age:   23


You are eligible to vote.


##### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [25]:
marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Enter your marks:   85


Grade: B


##### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [26]:
num = int(input("Enter a number: "))

if num > 0:
    print("Number is positive")
    
    if num % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")
        
elif num == 0:
    print("Number is zero")
    
else:
    print("Number is negative")

Enter a number:   20


Number is positive
It is also even


#### Section B: Numpy

##### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [35]:
import numpy as np

# scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

# 2D array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D Array:\n", arr_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [29]:
import numpy as np

arr = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:\n", arr)

4x4 Random Array:
 [[95 58 33  1]
 [35 98 87 63]
 [50 75 55 30]
 [27 18 51 49]]


##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [1]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


#### Section C: Exploring Pandas

##### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [37]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ravi", "Anu", "Kiran", "Megha", "Arun", "Divya", "Ravi", "Sneha", "Rahul", "Anu"],
    "Age": [22, 23, 21, 24, 22, 23, 22, 25, 24, 23],
    "City": ["Bangalore", "Mysore", "Delhi", "Mumbai", "Chennai", "Bangalore", "Bangalore", "Delhi", "Mumbai", "Mysore"],
    "Salary": [25000, 30000, np.nan, 40000, 35000, np.nan, 25000, 45000, 40000, 30000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


Original DataFrame:
     Name  Age       City   Salary
0   Ravi   22  Bangalore  25000.0
1    Anu   23     Mysore  30000.0
2  Kiran   21      Delhi      NaN
3  Megha   24     Mumbai  40000.0
4   Arun   22    Chennai  35000.0
5  Divya   23  Bangalore      NaN
6   Ravi   22  Bangalore  25000.0
7  Sneha   25      Delhi  45000.0
8  Rahul   24     Mumbai  40000.0
9    Anu   23     Mysore  30000.0


##### -> Use .info(), .describe()

In [38]:
#info 
print("\nInfo:")
print(df.info())

# select columns
print("\nDescribe:")
print(df.describe())


Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Describe:
             Age        Salary
count  10.000000      8.000000
mean   22.900000  33750.000000
std     1.197219   7440.238091
min    21.000000  25000.000000
25%    22.000000  28750.000000
50%    23.000000  32500.000000
75%    23.750000  40000.000000
max    25.000000  45000.000000


##### -> Select 'Name' and 'City' columns
##### -> Drop 'City' column

In [39]:
# select columns
print("\nSelected Columns (Name, City):")
print(df[["Name", "City"]])

# drop city column
df = df.drop("City", axis=1)
print("\nAfter Dropping 'City':\n", df)


Selected Columns (Name, City):
    Name       City
0   Ravi  Bangalore
1    Anu     Mysore
2  Kiran      Delhi
3  Megha     Mumbai
4   Arun    Chennai
5  Divya  Bangalore
6   Ravi  Bangalore
7  Sneha      Delhi
8  Rahul     Mumbai
9    Anu     Mysore

After Dropping 'City':
     Name  Age   Salary
0   Ravi   22  25000.0
1    Anu   23  30000.0
2  Kiran   21      NaN
3  Megha   24  40000.0
4   Arun   22  35000.0
5  Divya   23      NaN
6   Ravi   22  25000.0
7  Sneha   25  45000.0
8  Rahul   24  40000.0
9    Anu   23  30000.0


##### -> Fill any missing values in 'Salary' column with the mean

In [40]:
# fill missing salary with mean
mean_salary = df["Salary"].mean()
df["Salary"].fillna(mean_salary, inplace=True)
print("\nAfter Filling Missing Salary:\n", df)


After Filling Missing Salary:
     Name  Age   Salary
0   Ravi   22  25000.0
1    Anu   23  30000.0
2  Kiran   21  33750.0
3  Megha   24  40000.0
4   Arun   22  35000.0
5  Divya   23  33750.0
6   Ravi   22  25000.0
7  Sneha   25  45000.0
8  Rahul   24  40000.0
9    Anu   23  30000.0


C:\Users\Rakshitha\AppData\Local\Temp\ipykernel_25924\3628621846.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(mean_salary, inplace=True)


##### -> Remove any duplicate rows

In [41]:
# remove duplicates
df = df.drop_duplicates()
print("\nAfter Removing Duplicates:\n", df)


After Removing Duplicates:
     Name  Age   Salary
0   Ravi   22  25000.0
1    Anu   23  30000.0
2  Kiran   21  33750.0
3  Megha   24  40000.0
4   Arun   22  35000.0
5  Divya   23  33750.0
7  Sneha   25  45000.0
8  Rahul   24  40000.0
